services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobs-portal-api
    env_file:
      - .env
    environment:
      - PORT=8000
    ports:
      - '8000:8000'
    depends_on:
      - apiDB
    volumes:
      - ./config/:/app/config
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - jobs-portal

  apiDB:
    image: postgres:16.4-bookworm
    restart: always
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    container_name: jobs-portal-db
    volumes:
      - jobs-portal-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - jobs-portal

volumes:
  jobs-portal-data: ~

networks:
  jobs-portal:
    driver: bridge